// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1_U0rAGfcrJasxIQx8EW4mgsS82wFD_c',
    appId: '1:280656726585:web:d05a7308dfbbf0fb0adbe8',
    messagingSenderId: '280656726585',
    projectId: 'tyr-login',
    authDomain: 'tyr-login.firebaseapp.com',
    storageBucket: 'tyr-login.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJRzswnWO1HIf8nuCEUdHUsv8BJGjBMsg',
    appId: '1:280656726585:android:97415d4658c79a860adbe8',
    messagingSenderId: '280656726585',
    projectId: 'tyr-login',
    storageBucket: 'tyr-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2cTIK684HDmaCRrlQRDDzqjvRTh9dx74',
    appId: '1:280656726585:ios:69e930e03b496bdd0adbe8',
    messagingSenderId: '280656726585',
    projectId: 'tyr-login',
    storageBucket: 'tyr-login.appspot.com',
    iosClientId:
        '280656726585-j7vbltpciek0oucsuvsfdsug4505eiao.apps.googleusercontent.com',
    iosBundleId: 'com.example.tyr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2cTIK684HDmaCRrlQRDDzqjvRTh9dx74',
    appId: '1:280656726585:ios:69e930e03b496bdd0adbe8',
    messagingSenderId: '280656726585',
    projectId: 'tyr-login',
    storageBucket: 'tyr-login.appspot.com',
    iosClientId:
        '280656726585-j7vbltpciek0oucsuvsfdsug4505eiao.apps.googleusercontent.com',
    iosBundleId: 'com.example.tyr',
  );
}
